// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: wenworpc/elastic.proto

package elastic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GlobalSearchClient is the client API for GlobalSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GlobalSearchClient interface {
	GetSearch(ctx context.Context, in *GlobalSearchRequest, opts ...grpc.CallOption) (*GlobalSearchResponse, error)
}

type globalSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewGlobalSearchClient(cc grpc.ClientConnInterface) GlobalSearchClient {
	return &globalSearchClient{cc}
}

func (c *globalSearchClient) GetSearch(ctx context.Context, in *GlobalSearchRequest, opts ...grpc.CallOption) (*GlobalSearchResponse, error) {
	out := new(GlobalSearchResponse)
	err := c.cc.Invoke(ctx, "/wenworpc.elastic.GlobalSearch/getSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlobalSearchServer is the server API for GlobalSearch service.
// All implementations must embed UnimplementedGlobalSearchServer
// for forward compatibility
type GlobalSearchServer interface {
	GetSearch(context.Context, *GlobalSearchRequest) (*GlobalSearchResponse, error)
	mustEmbedUnimplementedGlobalSearchServer()
}

// UnimplementedGlobalSearchServer must be embedded to have forward compatible implementations.
type UnimplementedGlobalSearchServer struct {
}

func (UnimplementedGlobalSearchServer) GetSearch(context.Context, *GlobalSearchRequest) (*GlobalSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearch not implemented")
}
func (UnimplementedGlobalSearchServer) mustEmbedUnimplementedGlobalSearchServer() {}

// UnsafeGlobalSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlobalSearchServer will
// result in compilation errors.
type UnsafeGlobalSearchServer interface {
	mustEmbedUnimplementedGlobalSearchServer()
}

func RegisterGlobalSearchServer(s grpc.ServiceRegistrar, srv GlobalSearchServer) {
	s.RegisterService(&GlobalSearch_ServiceDesc, srv)
}

func _GlobalSearch_GetSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalSearchServer).GetSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wenworpc.elastic.GlobalSearch/getSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalSearchServer).GetSearch(ctx, req.(*GlobalSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GlobalSearch_ServiceDesc is the grpc.ServiceDesc for GlobalSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GlobalSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wenworpc.elastic.GlobalSearch",
	HandlerType: (*GlobalSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSearch",
			Handler:    _GlobalSearch_GetSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wenworpc/elastic.proto",
}
