# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from wenworpc import channel_pb2 as wenworpc_dot_channel__pb2


class ChannelPtmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getChannel = channel.unary_unary(
                '/wenworpc.channel.ChannelPtm/getChannel',
                request_serializer=wenworpc_dot_channel__pb2.ChannelPtRequest.SerializeToString,
                response_deserializer=wenworpc_dot_channel__pb2.ChannelPtResponse.FromString,
                )


class ChannelPtmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelPtmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.getChannel,
                    request_deserializer=wenworpc_dot_channel__pb2.ChannelPtRequest.FromString,
                    response_serializer=wenworpc_dot_channel__pb2.ChannelPtResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wenworpc.channel.ChannelPtm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChannelPtm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wenworpc.channel.ChannelPtm/getChannel',
            wenworpc_dot_channel__pb2.ChannelPtRequest.SerializeToString,
            wenworpc_dot_channel__pb2.ChannelPtResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
