# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wenworpc/channel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wenworpc import common_pb2 as wenworpc_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wenworpc/channel.proto',
  package='wenworpc.channel',
  syntax='proto3',
  serialized_options=b'\n\024com.wenworpc.channelZ0git.wenwo.com/wenwo/wenworpc/go-wenworpc/channel',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16wenworpc/channel.proto\x12\x10wenworpc.channel\x1a\x15wenworpc/common.proto\"C\n\x0f\x43hannelPlatform\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x61\x62struct\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\\\n\x10\x43hannelPtRequest\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\x10\n\x08sync_way\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\r\x12\x10\n\x08pagesize\x18\x04 \x01(\r\"c\n\x11\x43hannelPtResponse\x12\x1e\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x0f.wenworpc.Error\x12.\n\x03\x63pt\x18\x02 \x03(\x0b\x32!.wenworpc.channel.ChannelPlatform2e\n\nChannelPtm\x12W\n\ngetChannel\x12\".wenworpc.channel.ChannelPtRequest\x1a#.wenworpc.channel.ChannelPtResponse\"\x00\x42H\n\x14\x63om.wenworpc.channelZ0git.wenwo.com/wenwo/wenworpc/go-wenworpc/channelb\x06proto3'
  ,
  dependencies=[wenworpc_dot_common__pb2.DESCRIPTOR,])




_CHANNELPLATFORM = _descriptor.Descriptor(
  name='ChannelPlatform',
  full_name='wenworpc.channel.ChannelPlatform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='wenworpc.channel.ChannelPlatform.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='abstruct', full_name='wenworpc.channel.ChannelPlatform.abstruct', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='wenworpc.channel.ChannelPlatform.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=134,
)


_CHANNELPTREQUEST = _descriptor.Descriptor(
  name='ChannelPtRequest',
  full_name='wenworpc.channel.ChannelPtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='wenworpc.channel.ChannelPtRequest.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sync_way', full_name='wenworpc.channel.ChannelPtRequest.sync_way', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='wenworpc.channel.ChannelPtRequest.page', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='wenworpc.channel.ChannelPtRequest.pagesize', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=228,
)


_CHANNELPTRESPONSE = _descriptor.Descriptor(
  name='ChannelPtResponse',
  full_name='wenworpc.channel.ChannelPtResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='wenworpc.channel.ChannelPtResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpt', full_name='wenworpc.channel.ChannelPtResponse.cpt', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=329,
)

_CHANNELPTRESPONSE.fields_by_name['error'].message_type = wenworpc_dot_common__pb2._ERROR
_CHANNELPTRESPONSE.fields_by_name['cpt'].message_type = _CHANNELPLATFORM
DESCRIPTOR.message_types_by_name['ChannelPlatform'] = _CHANNELPLATFORM
DESCRIPTOR.message_types_by_name['ChannelPtRequest'] = _CHANNELPTREQUEST
DESCRIPTOR.message_types_by_name['ChannelPtResponse'] = _CHANNELPTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChannelPlatform = _reflection.GeneratedProtocolMessageType('ChannelPlatform', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELPLATFORM,
  '__module__' : 'wenworpc.channel_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.channel.ChannelPlatform)
  })
_sym_db.RegisterMessage(ChannelPlatform)

ChannelPtRequest = _reflection.GeneratedProtocolMessageType('ChannelPtRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELPTREQUEST,
  '__module__' : 'wenworpc.channel_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.channel.ChannelPtRequest)
  })
_sym_db.RegisterMessage(ChannelPtRequest)

ChannelPtResponse = _reflection.GeneratedProtocolMessageType('ChannelPtResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELPTRESPONSE,
  '__module__' : 'wenworpc.channel_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.channel.ChannelPtResponse)
  })
_sym_db.RegisterMessage(ChannelPtResponse)


DESCRIPTOR._options = None

_CHANNELPTM = _descriptor.ServiceDescriptor(
  name='ChannelPtm',
  full_name='wenworpc.channel.ChannelPtm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=331,
  serialized_end=432,
  methods=[
  _descriptor.MethodDescriptor(
    name='getChannel',
    full_name='wenworpc.channel.ChannelPtm.getChannel',
    index=0,
    containing_service=None,
    input_type=_CHANNELPTREQUEST,
    output_type=_CHANNELPTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHANNELPTM)

DESCRIPTOR.services_by_name['ChannelPtm'] = _CHANNELPTM

# @@protoc_insertion_point(module_scope)
