# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wenworpc/elastic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wenworpc import common_pb2 as wenworpc_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wenworpc/elastic.proto',
  package='wenworpc.elastic',
  syntax='proto3',
  serialized_options=b'\n\024com.wenworpc.elasticZ0git.wenwo.com/wenwo/wenworpc/go-wenworpc/elastic',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16wenworpc/elastic.proto\x12\x10wenworpc.elastic\x1a\x15wenworpc/common.proto\"\xb5\x01\n\x13GlobalSearchContent\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x14\n\x0c\x61uthor_photo\x18\x03 \x01(\t\x12\x0b\n\x03img\x18\x04 \x01(\t\x12\r\n\x05views\x18\x05 \x01(\r\x12\x0c\n\x04like\x18\x06 \x01(\r\x12\x0e\n\x06\x61nswer\x18\x07 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x08 \x01(\t\x12\r\n\x05price\x18\t \x01(\t\x12\x0f\n\x07\x63reated\x18\n \x01(\t\"_\n\x13GlobalSearchRequest\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\x10\n\x08sync_wau\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\r\x12\x10\n\x08pagesize\x18\x04 \x01(\r\"q\n\x14GlobalSearchResponse\x12\x1e\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x0f.wenworpc.Error\x12\x39\n\ngs_content\x18\x02 \x03(\x0b\x32%.wenworpc.elastic.GlobalSearchContent2l\n\x0cGlobalSearch\x12\\\n\tgetSearch\x12%.wenworpc.elastic.GlobalSearchRequest\x1a&.wenworpc.elastic.GlobalSearchResponse\"\x00\x42H\n\x14\x63om.wenworpc.elasticZ0git.wenwo.com/wenwo/wenworpc/go-wenworpc/elasticb\x06proto3'
  ,
  dependencies=[wenworpc_dot_common__pb2.DESCRIPTOR,])




_GLOBALSEARCHCONTENT = _descriptor.Descriptor(
  name='GlobalSearchContent',
  full_name='wenworpc.elastic.GlobalSearchContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='wenworpc.elastic.GlobalSearchContent.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='wenworpc.elastic.GlobalSearchContent.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author_photo', full_name='wenworpc.elastic.GlobalSearchContent.author_photo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img', full_name='wenworpc.elastic.GlobalSearchContent.img', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='views', full_name='wenworpc.elastic.GlobalSearchContent.views', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='like', full_name='wenworpc.elastic.GlobalSearchContent.like', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='answer', full_name='wenworpc.elastic.GlobalSearchContent.answer', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='wenworpc.elastic.GlobalSearchContent.content', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='wenworpc.elastic.GlobalSearchContent.price', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created', full_name='wenworpc.elastic.GlobalSearchContent.created', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=249,
)


_GLOBALSEARCHREQUEST = _descriptor.Descriptor(
  name='GlobalSearchRequest',
  full_name='wenworpc.elastic.GlobalSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='wenworpc.elastic.GlobalSearchRequest.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sync_wau', full_name='wenworpc.elastic.GlobalSearchRequest.sync_wau', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='wenworpc.elastic.GlobalSearchRequest.page', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='wenworpc.elastic.GlobalSearchRequest.pagesize', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=346,
)


_GLOBALSEARCHRESPONSE = _descriptor.Descriptor(
  name='GlobalSearchResponse',
  full_name='wenworpc.elastic.GlobalSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='wenworpc.elastic.GlobalSearchResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gs_content', full_name='wenworpc.elastic.GlobalSearchResponse.gs_content', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=461,
)

_GLOBALSEARCHRESPONSE.fields_by_name['error'].message_type = wenworpc_dot_common__pb2._ERROR
_GLOBALSEARCHRESPONSE.fields_by_name['gs_content'].message_type = _GLOBALSEARCHCONTENT
DESCRIPTOR.message_types_by_name['GlobalSearchContent'] = _GLOBALSEARCHCONTENT
DESCRIPTOR.message_types_by_name['GlobalSearchRequest'] = _GLOBALSEARCHREQUEST
DESCRIPTOR.message_types_by_name['GlobalSearchResponse'] = _GLOBALSEARCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlobalSearchContent = _reflection.GeneratedProtocolMessageType('GlobalSearchContent', (_message.Message,), {
  'DESCRIPTOR' : _GLOBALSEARCHCONTENT,
  '__module__' : 'wenworpc.elastic_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.elastic.GlobalSearchContent)
  })
_sym_db.RegisterMessage(GlobalSearchContent)

GlobalSearchRequest = _reflection.GeneratedProtocolMessageType('GlobalSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _GLOBALSEARCHREQUEST,
  '__module__' : 'wenworpc.elastic_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.elastic.GlobalSearchRequest)
  })
_sym_db.RegisterMessage(GlobalSearchRequest)

GlobalSearchResponse = _reflection.GeneratedProtocolMessageType('GlobalSearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _GLOBALSEARCHRESPONSE,
  '__module__' : 'wenworpc.elastic_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.elastic.GlobalSearchResponse)
  })
_sym_db.RegisterMessage(GlobalSearchResponse)


DESCRIPTOR._options = None

_GLOBALSEARCH = _descriptor.ServiceDescriptor(
  name='GlobalSearch',
  full_name='wenworpc.elastic.GlobalSearch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=463,
  serialized_end=571,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSearch',
    full_name='wenworpc.elastic.GlobalSearch.getSearch',
    index=0,
    containing_service=None,
    input_type=_GLOBALSEARCHREQUEST,
    output_type=_GLOBALSEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GLOBALSEARCH)

DESCRIPTOR.services_by_name['GlobalSearch'] = _GLOBALSEARCH

# @@protoc_insertion_point(module_scope)
