# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wenworpc/scrapy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wenworpc import common_pb2 as wenworpc_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wenworpc/scrapy.proto',
  package='wenworpc.scrapy',
  syntax='proto3',
  serialized_options=b'\n\023com.wenworpc.scrapyZ/git.wenwo.com/wenwo/wenworpc/go-wenworpc/scrapy',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15wenworpc/scrapy.proto\x12\x0fwenworpc.scrapy\x1a\x15wenworpc/common.proto\"p\n\rArticleScrapy\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x10\n\x08\x61\x62struct\x18\x05 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\"N\n\x14\x41rticleScrapyRequest\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\r\x12\x10\n\x08pagesize\x18\x03 \x01(\r\"d\n\x15\x41rticleScrapyResponse\x12\x1e\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x0f.wenworpc.Error\x12+\n\x03\x61\x65s\x18\x02 \x03(\x0b\x32\x1e.wenworpc.scrapy.ArticleScrapy2h\n\x06Scrapy\x12^\n\x0bgetArticles\x12%.wenworpc.scrapy.ArticleScrapyRequest\x1a&.wenworpc.scrapy.ArticleScrapyResponse\"\x00\x42\x46\n\x13\x63om.wenworpc.scrapyZ/git.wenwo.com/wenwo/wenworpc/go-wenworpc/scrapyb\x06proto3'
  ,
  dependencies=[wenworpc_dot_common__pb2.DESCRIPTOR,])




_ARTICLESCRAPY = _descriptor.Descriptor(
  name='ArticleScrapy',
  full_name='wenworpc.scrapy.ArticleScrapy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='wenworpc.scrapy.ArticleScrapy.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='wenworpc.scrapy.ArticleScrapy.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform', full_name='wenworpc.scrapy.ArticleScrapy.platform', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='wenworpc.scrapy.ArticleScrapy.url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='abstruct', full_name='wenworpc.scrapy.ArticleScrapy.abstruct', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='wenworpc.scrapy.ArticleScrapy.content', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=177,
)


_ARTICLESCRAPYREQUEST = _descriptor.Descriptor(
  name='ArticleScrapyRequest',
  full_name='wenworpc.scrapy.ArticleScrapyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='wenworpc.scrapy.ArticleScrapyRequest.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='wenworpc.scrapy.ArticleScrapyRequest.page', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pagesize', full_name='wenworpc.scrapy.ArticleScrapyRequest.pagesize', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=257,
)


_ARTICLESCRAPYRESPONSE = _descriptor.Descriptor(
  name='ArticleScrapyResponse',
  full_name='wenworpc.scrapy.ArticleScrapyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='wenworpc.scrapy.ArticleScrapyResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aes', full_name='wenworpc.scrapy.ArticleScrapyResponse.aes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=359,
)

_ARTICLESCRAPYRESPONSE.fields_by_name['error'].message_type = wenworpc_dot_common__pb2._ERROR
_ARTICLESCRAPYRESPONSE.fields_by_name['aes'].message_type = _ARTICLESCRAPY
DESCRIPTOR.message_types_by_name['ArticleScrapy'] = _ARTICLESCRAPY
DESCRIPTOR.message_types_by_name['ArticleScrapyRequest'] = _ARTICLESCRAPYREQUEST
DESCRIPTOR.message_types_by_name['ArticleScrapyResponse'] = _ARTICLESCRAPYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArticleScrapy = _reflection.GeneratedProtocolMessageType('ArticleScrapy', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLESCRAPY,
  '__module__' : 'wenworpc.scrapy_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.scrapy.ArticleScrapy)
  })
_sym_db.RegisterMessage(ArticleScrapy)

ArticleScrapyRequest = _reflection.GeneratedProtocolMessageType('ArticleScrapyRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLESCRAPYREQUEST,
  '__module__' : 'wenworpc.scrapy_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.scrapy.ArticleScrapyRequest)
  })
_sym_db.RegisterMessage(ArticleScrapyRequest)

ArticleScrapyResponse = _reflection.GeneratedProtocolMessageType('ArticleScrapyResponse', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLESCRAPYRESPONSE,
  '__module__' : 'wenworpc.scrapy_pb2'
  # @@protoc_insertion_point(class_scope:wenworpc.scrapy.ArticleScrapyResponse)
  })
_sym_db.RegisterMessage(ArticleScrapyResponse)


DESCRIPTOR._options = None

_SCRAPY = _descriptor.ServiceDescriptor(
  name='Scrapy',
  full_name='wenworpc.scrapy.Scrapy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=361,
  serialized_end=465,
  methods=[
  _descriptor.MethodDescriptor(
    name='getArticles',
    full_name='wenworpc.scrapy.Scrapy.getArticles',
    index=0,
    containing_service=None,
    input_type=_ARTICLESCRAPYREQUEST,
    output_type=_ARTICLESCRAPYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCRAPY)

DESCRIPTOR.services_by_name['Scrapy'] = _SCRAPY

# @@protoc_insertion_point(module_scope)
