# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from wenworpc import scrapy_pb2 as wenworpc_dot_scrapy__pb2


class ScrapyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getArticles = channel.unary_unary(
                '/wenworpc.scrapy.Scrapy/getArticles',
                request_serializer=wenworpc_dot_scrapy__pb2.ArticleScrapyRequest.SerializeToString,
                response_deserializer=wenworpc_dot_scrapy__pb2.ArticleScrapyResponse.FromString,
                )


class ScrapyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScrapyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.getArticles,
                    request_deserializer=wenworpc_dot_scrapy__pb2.ArticleScrapyRequest.FromString,
                    response_serializer=wenworpc_dot_scrapy__pb2.ArticleScrapyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wenworpc.scrapy.Scrapy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scrapy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wenworpc.scrapy.Scrapy/getArticles',
            wenworpc_dot_scrapy__pb2.ArticleScrapyRequest.SerializeToString,
            wenworpc_dot_scrapy__pb2.ArticleScrapyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
